background = rgb(1a1b26)
base = rgb(414868)
text = rgb(c0caf5)
alternate_base = rgb(414868)
accent = rgb(7aa2f7)
accent_secondary = rgb(7aa2f7)

desktop_icons = true

h1_size = 18
h2_size = 16
h3_size = 14
font_size = 12
small_font_size = 10

font_family = RecMonoLinear Nerd Font
font_family_monospace = CaskaydiaCove Nerd Font
