$foreground = rgb(d8dee9)
$foregroundAlpha = d8dee9

$background = rgb(2e3440)
$backgroundAlpha = 2e3440

$cursor = rgb(88c0d0)
$cursorAlpha = 88c0d0

$comment = rgb(616e88)
$commentAlpha = 616e88

$red = rgb(bf616a)
$redAlpha = bf616a

$orange = rgb(d08770)
$orangeAlpha = d08770

$yellow = rgb(ebcb8b)
$yellowAlpha = ebcb8b

$green = rgb(a3be8c)
$greenAlpha = a3be8c

$blue = rgb(81a1c1)
$blueAlpha = 81a1c1

$purple = rgb(b48ead)
$purpleAlpha = b48ead

$cyan = rgb(88c0d0)
$cyanAlpha = 88c0d0

$magenta = rgb(b48ead)
$magentaAlpha = b48ead

$black = rgb(2e3440)
$blackAlpha = 2e3440

$bright_black = rgb(4c566a)
$bright_blackAlpha = 4c566a

$bright_white = rgb(e5e9f0)
$bright_whiteAlpha = e5e9f0

$text = rgb(d8dee9)
$textAlpha = d8dee9

$base = rgb(2e3440)
$baseAlpha = 2e3440

$overlay = rgb(3b4252)
$overlayAlpha = 3b4252

$subtext = rgb(aeb7c2)
$subtextAlpha = aeb7c2
