$foreground = rgb(c0caf5)
$foregroundAlpha = c0caf5

$background = rgb(1a1b26)
$backgroundAlpha = 1a1b26

$cursor = rgb(bb9af7)
$cursorAlpha = bb9af7

$comment = rgb(565f89)
$commentAlpha = 565f89

$red = rgb(f7768e)
$redAlpha = f7768e

$orange = rgb(ff9e64)
$orangeAlpha = ff9e64

$yellow = rgb(e0af68)
$yellowAlpha = e0af68

$green = rgb(9ece6a)
$greenAlpha = 9ece6a

$blue = rgb(7aa2f7)
$blueAlpha = 7aa2f7

$purple = rgb(9d7cd8)
$purpleAlpha = 9d7cd8

$cyan = rgb(7dcfff)
$cyanAlpha = 7dcfff

$magenta = rgb(bb9af7)
$magentaAlpha = bb9af7

$black = rgb(15161e)
$blackAlpha = 15161e

$bright_black = rgb(414868)
$bright_blackAlpha = 414868

$bright_white = rgb(a9b1d6)
$bright_whiteAlpha = a9b1d6

$text = rgb(a9b1d6)
$textAlpha = a9b1d6

$base = rgb(1a1b26)
$baseAlpha = 1a1b26

$overlay = rgb(292e42)
$overlayAlpha = 292e42

$subtext = rgb(9aa5ce)
$subtextAlpha = 9aa5ce
